### PR TITLE
build: Support cmake to build and install

### PR DESCRIPTION
**Pull request by rzr**
This can help to support yocto

For the record I built it using

  export CFLAGS='-I${sysroot}/usr/local/include/ -DLV_CONF_INCLUDE_SIMPLE=1'
  cmake . && make && make install

Relate-to: https://github.com/lvgl/lvgl/issues/2534
Signed-off-by: Philippe Coval <philippe.coval@astrolabe.coop>

### CODE REVIEW

**Comment by kisvegabor** [comment]
This repo was just merged into the main lvgl repo. 
Is this update still required?

**Comment by rzr** [comment]
maybe not let me check again once my other cmake files changes are merged

**Comment by rzr** [comment]
well It's desirable for a project which is using only latest release, btw any roadmap for upcoming one ?

**Comment by rzr** [comment]
The reason is that default bitbake recipe curently relies on default settings (except wayland) so it could be helpful to support this as thirdparty lib until released.

Relate-to: https://github.com/lvgl/lvgl/issues/2534
Cc: @embeddedt

**Comment by rzr** [comment]
Can this change be merged It wont cause any issue and I might upstream bitbake recipe since openembedded's lvgl uses default config with png disabled.

Relate-to: https://github.com/lvgl/lvgl/issues/2534

**Comment by kisvegabor** [comment]
Alright, merging. 

> well It's desirable for a project which is using only latest release, btw any roadmap for upcoming one ?


We are just thinking about fine-tuning our release policy (See https://github.com/lvgl/lvgl/issues/2573)
Anyway, we got enough features for a new minor version but I'd like clarify the release policy topic first.

**Comment by rzr** [comment]
May I request one last thing, can master branch be tagged ?

At worst case you can tag "v0.0.0" the intitial commit  ae88a69a9d69865b285b8f2efe67b3c37270bf23

**Comment by kisvegabor** [comment]
> May I request one last thing

It doesn't have to be the last :slightly_smiling_face: 


I've tagged the the current HEAD with v8.0.2. Is it ok?

**Comment by rzr** [comment]
perfect, let's track this https://github.com/openembedded/meta-openembedded/pull/454

BTW, feel to  remind me to update other recipes if I miss new tags on packaged projects in OE

**Pull request merged**
