### PR TITLE
fix bug: when the picture is bad it will cause double free

### PR DESCRIPTION
**Pull request by jianjunxia**

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you!

**Comment by jianjunxia** [comment]
> Thank you!

In addition, I have another question to ask. When the content of a picture is bad, do we have some kind of verification or clarification mechanism?，This is an important question for me

**Comment by kisvegabor** [comment]
Do you mean if the content of the image is broken?

**Comment by jianjunxia** [comment]
> Do you mean if the content of the image is broken?
Yes, I observe that I will keep opening this picture

**Comment by kisvegabor** [comment]
Would you expect to somehow mark the image as broken to ignore it immediately in the decoder_open function?

**Comment by jianjunxia** [comment]
yes,and does not affect the operation of the entire system and the use of other images



---Original---
From: "Gabor ***@***.***&gt;
Date: Wed, Jul 7, 2021 23:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lvgl/lv_lib_png] fix bug: when the picture is bad it will cause double free (#18)




 
Would you expect to somehow mark the image as broken to ignore it immediately in the decoder_open function?

**Comment by jianjunxia** [comment]
yes,and does not affect the operation of the entire system and the use of other images




---Original---
From: "Gabor ***@***.***&gt;
Date: Wed, Jul 7, 2021 23:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lvgl/lv_lib_png] fix bug: when the picture is bad it will cause double free (#18)




 
Would you expect to somehow mark the image as broken to ignore it immediately in the decoder_open function?

**Comment by kisvegabor** [comment]
There is no such mechanism in LVGL at this moment. 

What is the use case when a PNG can be broken (incorrectly encoded)?

**Comment by jianjunxia** [comment]
> There is no such mechanism in LVGL at this moment.
> 
> What is the use case when a PNG can be broken (incorrectly encoded)?

this is my test code：
```c
#define TY_IMG_TEST "S:" TY_IMG_PATH "bad.png"
STATIC OPERATE_RET  gui_socket_set_img(lv_obj_t *obj)
{
    lv_obj_t *socket_img=lv_img_create(obj,NULL);
    lv_img_set_src(socket_img, TY_IMG_TEST);
    lv_obj_align(socket_img, NULL, LV_ALIGN_CENTER,0, 0);
    return OPRT_OK;
}
```
**Because there is no picture security and bottoming mechanism, we are worried that our pictures are bad, which will affect our system，At present, our equipment is already in production, if the picture is broken, it will cause our equipment to crash**

Can this problem be solved or circumvented by adjusting the current code sequence?

**Comment by kisvegabor** [comment]
What if you try to open the image with `lv_img_decoder_open` before setting it in `lv_img_set_src`? If it's incorrect you can set a placeholder image instead.

**Comment by jianjunxia** [comment]
> What if you try to open the image with `lv_img_decoder_open` before setting it in `lv_img_set_src`? If it's incorrect you can set a placeholder image instead.
set a placeholder image instead. What does that mean?

**Comment by jianjunxia** [comment]
> What if you try to open the image with `lv_img_decoder_open` before setting it in `lv_img_set_src`? If it's incorrect you can set a placeholder image instead.

set a placeholder image instead. What does that mean?

**Comment by embeddedt** [comment]
You can convert an image that says "Error" or something similar on it, and pass it to `lv_img_set_src` if `lv_img_decoder_open` fails.

**Comment by jianjunxia** [comment]
> You can convert an image that says "Error" or something similar on it, and pass it to `lv_img_set_src` if `lv_img_decoder_open` fails.

OK, I will try it tomorrow. I will consult you if I have any questions. Thanks for your answers

**Pull request merged**
